# Generated by Django 4.0 on 2021-12-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RunSQL("INSERT INTO article_board (reg_date, update_date, name) VALUES (NOW(), NOW(), '공지사항');"),
        migrations.AddField(
            model_name='article',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.board'),
            preserve_default=False,
        ),
    ]
